### ISSUE TITLE
Code sample links are broken

### ISSUE THREAD

**Issue by dkontyko** [MicrosoftDocs/office-developer-exchange-docs#180]
On https://github.com/MicrosoftDocs/office-developer-exchange-docs/blob/main/docs/transport-agents/transport-agent-code-samples-for-exchange-2013.md, the code sample links point to code.msdn.microsoft.com, which no longer exists. I am redirected to https://docs.microsoft.com/en-us/samples/browse/?redirectedfrom=MSDN-samples, but that is just the home page of new code samples, not the new location (if it exists) of the sample that I clicked on.

**Comment by lindalu-MSFT** [comment]
Hi thanks for reporting this. I removed the table with the broken links.
