### ISSUE TITLE
Links are not available for adding service principal

### ISSUE THREAD

**Issue by durgadas54** [MicrosoftDocs/office-developer-exchange-docs#288]
Hi,
As Document mentions below command to add service principal
[Docs](https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth)

New-ServicePrincipal -AppId <APPLICATION_ID> -ServiceId <OBJECT_ID> [-Organization <ORGANIZATION_ID>]***

But there is no such service principal even the link given then descriptions are broken for [New-ServicePrincipal cmdlet](https://docs.microsoft.com/en-us/powershell/module/exchange/new-serviceprincipal) and [Get-ServicePrincipal cmdlet](https://docs.microsoft.com/en-us/powershell/module/exchange/get-serviceprincipal)

**Comment by lindalu-MSFT** [comment]
**New-ServicePrincial** 
https://docs.microsoft.com/powershell/module/exchange/new-serviceprincipal 
**Get-ServicePrincipal** 
https://docs.microsoft.com/powershell/module/exchange/get-serviceprincipal

**Examples:**
`New-ServicePrincipal -AppId 71487acd-ec93-476d-bd0e-6c8b31831053 -ServiceId 6233fba6-0198-4277-892f-9275bf728bcc`
and
`Get-ServicePrincipal -Identity ca73fffa-cedb-4b84-860f-d7fb8aa8a6c1 | Format-List
`
