### ISSUE TITLE
How to run New-ServicePrincipal

### ISSUE THREAD

**Issue by alkampfergit** [MicrosoftDocs/office-developer-exchange-docs#300]
It could be a simple question, but I didn't find a way to run New-ServicePrincipal, I've imported various exchange module but still got 

```
New-ServicePrincipal: The term 'New-ServicePrincipal' is not recognized as a name of a cmdlet, function, script file, or executable program.
```

How can I run that cmdlet?

**Comment by lindalu-MSFT** [comment]
Hi @alkampfergit I think you figured this out, correct?
