### ISSUE TITLE
Immutability of EWS Folder IDs unclear

### ISSUE THREAD

**Issue by austinmccollum** [MicrosoftDocs/office-developer-exchange-docs#57]
**[ews-identifiers-in-exchange.md](https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/ews-identifiers-in-exchange#working-with-identifiers)** has a list of tips when working with identifiers.  The third bullet point, 

> Don't assume that your ID will always be valid if you need to retrieve the item at a later time. If an item is moved in the store, the ID can change because of the way a move is handled. An item is actually copied, and a new ID is generated, and then the original item is deleted.

should clarify this tip is for item IDs, but that folder IDs are in fact immutable.  Here's my recommended change for this:

_Don't assume that your item ID will always be valid if you need to retrieve the item at a later time. If an item is moved in the store, the ID can change because of the way a move is handled. An item is actually copied, and a new ID is generated, and then the original item is deleted.  Folder IDs however are immutable, and won't change when moved in the store._

**Comment by lindalu-MSFT** [comment]
@austinmccollum Thanks for the suggestion, I've incorporated it and will merge to live shortly. Please not that this repo is not currently monitored. I had another change to make and noticed your suggestion so I went ahead and fixed it.

**Comment by Shawnaldinho** [comment]
Immutability gives the impression folder IDs will never change. They regularly change as mailboxes are moved between exchange databases, something that will be increasingly common within elastic Exchange Online. Actual immutability would be extremely useful.
