### ISSUE TITLE
[LOC] Multiple invalid links in articles

### ISSUE THREAD

**Issue by OfficeGSX** [MicrosoftDocs/office-developer-exchange-docs#8]
Hello,

Please go through the attached excel list with the invalid links and fix them.

Thank you.

[ExchangeDevDocs_ENUS.xlsx](https://github.com/MicrosoftDocs/office-developer-exchange-docs/files/2204932/ExchangeDevDocs_ENUS.xlsx)

**Link to the CATS test:**
http://contentqa_cats/CheckResults/2018071600075/Report/

**Comment by Linda-Editor** [comment]
Fixed broken links and merged to master > live.
