### ISSUE TITLE
Code Samples are no longer available

### ISSUE THREAD

**Issue by behrouzamiri** [MicrosoftDocs/office-developer-exchange-docs#84]
Code Samples which are linked in [here](https://github.com/MicrosoftDocs/office-developer-exchange-docs/blob/master/docs/transport-agents/transport-agent-code-samples-for-exchange-2013.md) are no longer available.
resources were supposed to get moved to docs.microsoft.com/samples due to the "new code samples experience", however, there are no Exchange server Transport Agent code sample available there.
after searching [Microsoft Archive](https://github.com/microsoftarchive) it turns out that code samples are not available too.
this issue should be resolved because it made the documentation incomplete. we (users) need those samples to be able to develope transport agents.

**Comment by lindalu-MSFT** [comment]
Some exchange code samples [here](https://docs.microsoft.com/en-us/samples/browse/?redirectedfrom=MSDN-samples&term=exchange) and some in the Office developer gallery [here](https://developer.microsoft.com/en-us/office/gallery/?filterBy=Outlook,Samples).

**Comment by behrouzamiri** [comment]
> Some exchange code samples [here](https://docs.microsoft.com/en-us/samples/browse/?redirectedfrom=MSDN-samples&term=exchange) and some in the Office developer gallery [here](https://developer.microsoft.com/en-us/office/gallery/?filterBy=Outlook,Samples).

Dear linda,
Thank you very much for you support. I really appreciate that.
Unfortunately, Both of the provided links are not related to what that is mentioned within the document.
The document specifically refers to "Exchange Server Transport Agent" code samples. However, the links that you posted are about Outlook add-ins and things like that.

Transport agent code samples are entirely something different. I used to refer to those code samples and write code to create custom  Exchange Server transport agent. This is very important for us- lets not say users, instead, Microsoft solution providers, that customize solutions such as Microsoft Exchange Server to fit large enterprise needs- to have access to those code samples.

**Comment by behrouzamiri** [comment]
Needs your kind reconsideration and review.

Regards
Behrouz

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
