### ISSUE TITLE
Missing fields for MeetingResponse?

### ISSUE THREAD

**Issue by ecederstrand** [MicrosoftDocs/office-developer-exchange-docs#94]
https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-propose-a-new-meeting-time-by-using-ews-in-exchange mentions the `ProposedStart`, `ProposedEnd` and `AssociatedCalendarItemId` fields on the `MeetingResponse` item, but the documentation for `MeetingResponse` does not mention these fields:
https://github.com/MicrosoftDocs/office-developer-exchange-docs/blob/master/docs/web-service-reference/meetingresponse.md

Which of these is correct?

**Comment by lindalu-MSFT** [comment]
@ElizabethSamuel-MSFT Is this something you can look into or help reassign?

**Comment by lindalu-MSFT** [comment]
I added @jasonjoh to this request to update documentation.

**Comment by jasonjoh** [comment]
@ecederstrand the item in the "how to propose" topic is an AcceptItem, not a MeetingResponse. https://github.com/MicrosoftDocs/office-developer-exchange-docs/blob/master/docs/web-service-reference/acceptitem.md
