### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by RitchieFlick** [MicrosoftDocs/office-developer-exchange-docs#98]
The link in the following line directs to a 404 error:

https://github.com/MicrosoftDocs/office-developer-exchange-docs/blame/master/docs/exchange-web-services/get-started-with-ews-client-applications.md#L23

**Comment by lindalu-MSFT** [comment]
Updated to new Office dev center link.

**Comment by lindalu-MSFT** [comment]
Merged to live
